const sagaList = [
    'Dragon Ball',
    'Dragon Ball: The Path to Power',
    'Dragon Ball Z: The Movie - Dead Zone',
    'Saiyan Saga',
    "Dragon Ball Z: The Movie - The World's Strongest",
    'Dragon Ball Z: The Decisive Battle for the Whole Earth',
    'Dragon Ball Z: Super Saiyan Son Goku',
    'Planet Namek Saga',
    'Dragon Ball Z: A Lonesome, Final Battle - The Father of Z Warrior Kakarot, who Challenged Freeza',
    'Dragon Ball Z: The Outstanding Strongest vs. Strongest',
    'Dragon Ball Z: Clash!! 10 Billion Power Warriors',
    'Androids Saga',
    'Dragon Ball Z: Extreme Battle!! Three Great Super Saiyans',
    'Dragon Ball Z: Defiance in the Face of Despair!! The Remaining Super-Warriors: Gohan and Trunks',
    'Dragon Ball Z: Burn!! Hot Battle - Fierce Battle - Super Fierce Battle',
    'Cell Saga',
    'Trunks of the Future Timeline',
    'Dragon Ball Z Gaiden: Saiya-jin Zetsumetsu Keikaku',
    'Dragon Ball Z: The Last Minute of the Galaxy!! A Super Incredible Guy',
    'Other World Saga',
    'Great Saiyaman Saga',
    "Dragon Ball Z: Two Dangerous People! Super Warriors Can't Sleep",
    "Dragon Ball Z Defeat the Super Warrior!! I'll Be The Winner",
    'Majin Buu Saga',
    'Dragon Ball Z: Resurrection Fusion!! Goku and Vegeta',
    "Dragon Ball Z: Dragon Fist Explosion!! Who Will Do It If Goku Doesn't Do It?",
    'Dragon Ball Z: Battle of Gods',
    "Dragon Ball Z: Resurrection 'F'",
    'Universe 6 Saga',
    'Copy-Vegeta Saga',
    'Future Saga',
    'Universe Survival Saga',
    'Dragon Ball Super: Broly',
    'Dragon Ball Super: Super Hero',
    'Peaceful World Saga',
]

export default sagaList